### ISSUE TITLE
SDK tests and various drivers

### ISSUE THREAD

**Issue by stilett0** [ata4/glrage#1]
Greetings from VOGONS crew :) This isn't really an issue per se.

Your project was mentioned in this thread: http://www.vogons.org/viewtopic.php?f=9&t=36276

In case you have never seen it, Gona left this wonderful repository for ATi 3D Rage and Rage Pro fans:
http://gona.mactar.hu/ATI_3D_CIF/
It lists compatibility of different games with different cards with different drivers, plus links the ATI 3D Rage Pro SDK. :)

**Comment by ata4** [comment]
I know, and it has been a huge help for the development of the wrapper. :+1: 

I've also watched that thread and VOGONS in general and I'll see when I can join to provide help and more information about this project. Right now, I'm looking desperately for the ATI version of Wipeout, since it's one of the extremely hard to get exclusives that I really would like to support. Maybe one you guys can help me there. :)

**Comment by stilett0** [comment]
BTW - I'm still an admin for glcif on Sourceforge, martin gave it to me for reasons I don't quite remember (I think I suggested he license/package/document it better than dropping raw DLLs onto their hosting, and provide versioning info, which create a bit of a knee-jerk reaction), and I also helped release someone's old simple 3D CIF logger which we stashed on VOGONSDrivers.

Yes, I would recommend joining the forum and starting a thread dedicated to your project. "PC Emulation" is probably the best place.

**Comment by retrogcom** [comment]
ata4, contact "vetz" on VOGONS and I'm sure we can get to an agreement regarding other ATI versions.

**Comment by aybe** [comment]
Hi !

I can provide a CD image of Wipeout ATI edition, send me a PM @ http://www.wipeoutzone.com/forum/member.php?1556717-aybe if you're interested :D

EDIT : Been trying to run it in Win10, I do get the video playing but it crashes after ... any ideas ? thanks !

**Comment by ata4** [comment]
I've gotten a CD image already, but thanks for your support. I did some tests with TR1 and Assault Rigs under Win 10, but I can't say how well Wipeout is working there and whether there's compatibility issues with the wrapper or the game itself. My main machine still runs on Win 7, but I plan to update soon.

For Wipeout in general, there are some serious rendering bugs left that I haven't been able to fix, it seems that half of the polygons are missing for some reason.

**Comment by aybe** [comment]
Okay,

I am the author of WXX-Rebirth (a new engine for Wipeout using Unity) :dancer: 
http://www.wxx-rebirth.com/
https://www.youtube.com/watch?v=tnTPEOm29zw (this is the most recent video)

From what I can tell, in the game there are many polygons with incorrect culling, i.e. you must turn culling to off for proper rendering. I don't know whether such feature is in the ATI CIF SDK at all (this is an entirely new thing for me), but I guess that should be pretty cheap for you to test out whether it'd fix it up.

I have tried to debug the `glrage` project (Win10/VS2015) but I'm facing the following :
- game crashes
- screen becomes white and game is top-most window
- consequently I cannot break to inspect what's causing the crash (I must kill the game or VS)

Can you tell how on your end you do setup Visual Studio for debugging games ?

Thank you :D

**Comment by ata4** [comment]
Culling is certainly not part of CIF and as far as I can tell, the missing polygons are never send to the GPU in the first place and OpenGL has culling disabled on default, so the game engine must be responsible for this. I haven't been able to find the flag in the assembly so far, though. It's a Watcom compiler dialect and pretty difficult to understand.

And yeah, I have troubles debugging full-screen applications as well. If the crash happens before the DirectDraw emulation kicks in to take over the window management, there's not much debugging possible. Other than having a second screen, I don't know a workaround for this issue.

Right now, I'm using Win7 x64 and VS 2015 Update 1 and it works fine for me. But I've seen previous reports that Wipeout crashes on Windows 10 for some reason. Guess it's time for me to update Windows to properly reproduce this problem...

**Comment by aybe** [comment]
That's weird ... I believe you that Watcom is a pain to debug !

I've been able to temporarily alleviate that 'top-most' issue with a small utility to put VS window always on top (https://www.savardsoftware.com/turbotop/).

Now I can see that there are 2 exceptions occurring in a row but I see only 'External Code' in the stack and don't really know their origin. I guess I'll somehow have to work with WinDbg or something like it to try understand a bit more what's going on when I get a minute.

**Comment by ata4** [comment]
Okay, I have just updated to Windows 10, everything is working fine so far. I also have tested Wipeout, but it appears to work fine as well, so I would say Windows isn't to blame. Maybe it would be a good idea to open a new issue, since this talk is a bit off-topic here. :smile:

**Comment by aybe** [comment]
Yes, issue created here -> https://github.com/ata4/glrage/issues/2
