### ISSUE TITLE
[wine+mesa] GL_EXT_gpu_shader4 unsupported in fragment shader

### ISSUE THREAD

**Issue by AaronBPaden** [ata4/glrage#10]
This is potentially a bug in wine or in mesa, but I figured I would open up a bug report here first just in case. I'm using r10 here, so it shouldn't be a problem with compat profiles.

![screenshot from 2017-08-24 16-26-17](https://user-images.githubusercontent.com/1188012/29689884-68506d32-88ea-11e7-903b-0c95e9d7ca2f.png)

**Comment by whizse** [comment]
Removing the "#extension GL_EXT_gpu_shader4: enable" line and replacing textureSize2D with textureSize in ati3dcif.fsh seems to work.

**Comment by ata4** [comment]
Yep, that extension is indeed unnecessary.

**Comment by legluondunet** [comment]
Hello, I'm using Linux/Wine and I need a glrage version that includes this fix. I can not find it in the releases and I don't know how to compile MS code on Linux.
Could someone help me please?

**Comment by ata4** [comment]
A new build is not really necessary, since the change is in the shader code only. It's enough to replace the included ati3dcif.fsh with the [current version](https://github.com/ata4/glrage/raw/00ea78cad24577b89b557e0de7c101bb024aee69/ati3dcif/shaders/ati3dcif.fsh).

**Comment by legluondunet** [comment]
I replace the ati3dcif.fsh file by most recent one from your github.
But I have a graphic issue with it:

https://imgur.com/MGd6JwY
Lara's home picture back is invisible

Could you reproduce this issue on Windows?

**Comment by ata4** [comment]
First of all, sorry for the delay.

I'm not sure what's going on there in that screenshot, it seems that the color black is interpreted as alpha in all textures, even if they're not configured as such. But I can neither reproduce it on Windows, nor on my VirtualBox Ubuntu installation. I may have to switch to my native Ubuntu for further testing, which is currently not ready yet. It's probably better to open a separate issue for that bug.

Also, during my tests with Wine I've realized that I should link the Visual C++ runtime library statically. 😄

**Comment by legluondunet** [comment]
> First of all, sorry for the delay.

Thank you to take your time giving support to a Linux user.

> But I can neither reproduce it on Windows, nor on my VirtualBox Ubuntu installation.

I didn't precise but I'm using TombAti with HD textures, I think your last ati3dcif.fsh file is not compatible with TombATI.

> Also, during my tests with Wine I've realized that I should link the Visual C++ runtime library statically.

for the moment I use Winetricks:
`$ winetricks vcrun2015`

I finished my Lutris script, if you would test:
https://lutris.net/games/tomb-raider-i/
all 3 scripts called "TombATI HD".

**Comment by ata4** [comment]
Sounds like you're using the Glidos fork, which may be based on an older version of GLRage. This version doesn't have HD texture support right now, but one of my side projects is an improved wrapper specially for TombATI which kinda goes back to the roots of GLCIF, since it takes so much patching to make Tomb Raider 1 run properly. It will include HD texture support, among other things.

**Comment by legluondunet** [comment]
for information, my final receipt for TOMBAti to launch with Intel MESA on Linux/Wine:
export MESA_GL_VERSION_OVERRIDE=3.3
replace "textureSize2D" by "textureSize" in ati3dcif.fs
then it launches ok.
I updated my Lutris script with this changes, so it will be transparent for Linux users who will use it.
