### ISSUE TITLE
Wipeout crashes in Windows 10

### ISSUE THREAD

**Issue by aybe** [ata4/glrage#2]
The game crashes right after playing the video:

(actually it crashes 2 times in a row and pressing the Debug button does not start Visual Studio)

```
Faulting application name: WIPEOUT.EXE, version: 1.0.0.26, time stamp: 0x32134bd7
Faulting module name: WIPEOUT.EXE, version: 1.0.0.26, time stamp: 0x32134bd7
Exception code: 0xc0000005
Fault offset: 0x0006a09f
Faulting process id: 0x2dac
Faulting application start time: 0x01d15473af15d303
Faulting application path: C:\3D Rage Games\WipEout\WIPEOUT.EXE
Faulting module path: C:\3D Rage Games\WipEout\WIPEOUT.EXE
Report Id: 0609fa33-642d-4325-bd7f-a41a5e458309
Faulting package full name: 
Faulting package-relative application ID: 
```

```
Faulting application name: WIPEOUT.EXE, version: 1.0.0.26, time stamp: 0x32134bd7
Faulting module name: WIPEOUT.EXE, version: 1.0.0.26, time stamp: 0x32134bd7
Exception code: 0xc000041d
Fault offset: 0x0006a09f
Faulting process id: 0x2dac
Faulting application start time: 0x01d15473af15d303
Faulting application path: C:\3D Rage Games\WipEout\WIPEOUT.EXE
Faulting module path: C:\3D Rage Games\WipEout\WIPEOUT.EXE
Report Id: 264bb75a-df8f-4c7d-818f-365450865365
Faulting package full name: 
Faulting package-relative application ID: 
```

My configuration:

Windows 10
Core i7 4770
16 Gb RAM
ATI HD7850 2GB

Let me know if there's anything I can do over here to provide more details.

Thank you!

**Comment by aybe** [comment]
Here's further testing on my side:

With an Intel HD4600 game does crash without any message box, generates a crash dump though.

For both GPUs it seems that a null pointer is the cause in the EXE, however I can't know much more since it resumes from external code in the call stack.

I've also tried to disable all sort of optimizations on both GPUs without success...

I might be wrong but it seems that the game tries different pixel formats, fails on first but then it succeeds; intro video plays fine, but after that the game crashes.

**Comment by ata4** [comment]
You wrote that it crashes after playing the video. Strangely, I never see the video playing on my system. But maybe it helps to disable the video by renaming or moving WIPEOUT.MPG.

**Comment by aybe** [comment]
I've just tried to re-install the game without the video, the video still plays, I guess from the CD; and unfortunately game crashes exactly the same way :(

Any ideas on how to debug these crashes in WIPEOUT.EXE ? Been trying to use Windbg but since I don't know much about assembly it's kinda a shot in the dark ... Thanks !

**Comment by ata4** [comment]
Well, it should actually start even without a CD, but maybe that's why the videos aren't playing for me.

**Comment by aybe** [comment]
Removing the CD does not work for me: (all files have been copied from it first)

![2016-01-24 19_04_37-wipeout 95](https://cloud.githubusercontent.com/assets/1537591/12537991/7d974fb0-c2cd-11e5-8ee0-0d4a2d4825b6.png)

Do you have another version ? here is 1.0.0.26

![2016-01-24 19_03_57-checksum information](https://cloud.githubusercontent.com/assets/1537591/12537992/82faa20e-c2cd-11e5-8f6f-0e69352ab408.png)

**Comment by ata4** [comment]
Yeah, exact same version and hash. Strange... what does your Wipeout folder look like?

**Comment by aybe** [comment]
I've tried nearly all possible combinations: with/without video, copying everything from CD there.

I am trying to understand why I'm getting this NULL pointer,

![2016-01-24 20_03_00-cortana](https://cloud.githubusercontent.com/assets/1537591/12538259/b414db2c-c2d5-11e5-9d23-7365ba295ce7.png)

I've been trying to dig next to this PC3D_3DCIFINFO struct since slightly above this position there is 1Ch being pushed (size of that struct but older version) but well ... I mean it works for you so issue shouldn't be there ... If I could only revert a bit back to find the source but it's not easy without asm knowledge ...

Also, can you confirm that in ContextImpl::init, ChoosePixelFormat fails on first time, then I pass exception to program, next call works ?

Another thing, do you have an Nvidia card ? many times I've seen these being more tolerant in regards to older software.

**Comment by ata4** [comment]
As far as I can tell, 0x7D1B38 is supposed to contain a pointer to the primary DirectDraw surface, so I guess the DirectDraw initialization went wrong. I think it has something to do with the video playback, I know that video playback via MCI is somewhat bugged in Win10, but I just can't convince Wipeout to play its intro video for me.

Also, I actually have a HD 7850, too. And I would say Nvidia drivers are more strict than AMDs, at least in regards of OpenGL. In early versions, a short test on an Nvidia system revealed several errors in the shader files that AMD accepted silently. But I don't think this is a GPU issue at all.

**Comment by aybe** [comment]
Alright, thanks for the info !

I've been starting to study/comment/rename things in an IDA project, I'll see if I can bypass the video intro and if it changes anything.

Pretty weird that we get different results in mostly same configs ...

**Comment by ata4** [comment]
Okay... after some experimenting, I found out at least why the game behaves differently for me. Turns out the game loads its files differently when it can't find its registry entries. I installed the game on my retro system, since the installer is a 16 bit exe that doesn't work in x64, and simply copied the files to my main system. Since it worked out of box after copying the WIPEOUT folder from the CD, I didn't bother with the registry. With the registry entries, the game now behaves exactly as described.

Now I can try some further debugging and find out why DirectDraw isn't (re)initialized correctly.

**Comment by aybe** [comment]
Nice,

From what I've seen yesterday it's exactly what you said but I couldn't really dig further. That null reference seems to happen inside their Wndproc, that's all I can say.

For the installation you can run _WIPESET.EXE, it will install the game on x64, but you won't get that ATI wizard. I've just found out that it is not needed to install it at all in fact, following does work:
- create `C:\3D Rage Games\WipEout` folder
- copy `\WIPEOUT` folder in CD there
- set this registry :

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\3D Rage Games\Wipeout]
"Game Directory"="C:\\3D Rage Games\\WipEout"
"Movie Directory"="C:\\3D Rage Games\\WipEout"
"Data Directory"="C:\\3D Rage Games\\WipEout\\WIPEOUT"
"Resolution"="MEDI"
"Distance"="F"
"Texture"=""
"Sky"=""
"Help_File"="WIPEOUT.H"
```

Game runs without CD then.

Good luck for the debugging !

**Comment by ata4** [comment]
I can confirm that it has something to do with Wndproc. Something is sending WM_ACTIVATEAPP with wParam set to TRUE after the video has finished playing, which equals tabbing out and back in. The game assumes that DirectDrawCreate() has already been called at this point and resolves a NULL pointer. There's apparently a crude check using a flag at 0x6ADE8B that prevents this once, so I assume that WM_ACTIVATEAPP is send twice at least.

For now, I fixed that bug by preventing that flag from being set to 0, which effectively disables the entire alt+tab check. GLRage doesn't really need it anyway and the only side effect is that the game continues to run in the background when tabbed, so that should be fine. I also added another patch, which prevents the game from messing with the key repeat rate, which you may have noticed already :stuck_out_tongue: . I'll upload the new build tomorrow.

**Comment by aybe** [comment]
Outstanding!!! Can't wait to see that tomorrow :)

And yes, I noticed these annoying calls to SystemParametersInfo >_<

Well done and thank you !

**Comment by ata4** [comment]
Okay, I released r3 with this bug and several others fixed. It should now work for you as well, hopefully. :smiley:

**Comment by aybe** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: 

Simply amazing !

I will try do my best to understand/help fix on why there are missing/incorrectly drawn polygons.

Interestingly, on selection ship menu, ships are picking the other ship's polygon, I will binary compare the files and also try load and render the ATI version files in Unity with my code base, that might take a bit of time since I'll have to reorganize things a bit and I've seen this new SJR container differing from PSX version...

Will open a new issue for the rendering topic and keep you updated :D

Thanks, you rock :8ball:
