### ISSUE TITLE
Assault Rigs Application Error

### ISSUE THREAD

**Issue by Necko1701** [ata4/glrage#6]
Hi.

When I saw this project, I instantly grab my old CD of Assault Rigs and installed the game. Everything went fine but when start ARIGS.EXE, I got the following error message:

![unbenannt](https://cloud.githubusercontent.com/assets/20760369/17279679/007500c0-577b-11e6-97d4-916e8ba5cda7.png)

My system is a Windows 10 PC with 8GB RAM an an Geforce 680 GTX. I tried it on an PC of a friend but the same error occurs. 

Is it a problem with the wrapper or are some of the Files on the CD maybe broken?

**Comment by ata4** [comment]
What's the MD5 of your ARIGS.EXE? It should be ba489ef945cba4aad230052ea061eccb.

**Comment by Necko1701** [comment]
Yes, it is: ba489ef945cba4aad230052ea061eccb

**Comment by Necko1701** [comment]
Hello ata4

I just brought a new version of the game on eBay and I checked the files. It seems that the "RES.RDA" was broken on the CD.

Now Assault Rigs runs flawlessly on my System and it looks great. You even implemented 1080p!

Thank you very much!
