### ISSUE TITLE
Support for Resident Evil 2

### ISSUE THREAD

**Issue by kalash49** [ata4/glrage#7]
Hi. First of all thanks for your wonderful wrapper. I have one request for you. Is it possible to add support for PC version of Resident Evil 2, which is also support for ATI 3D Rage Pro series and some 3D Rage LT according to game readme. But when I try to launch this game with your wrapper I have error message "Pointer to original DirectDrawEnumerateA function not found". I hope there's a way to make RE2 works with your wrapper, thank you.

**Comment by ata4** [comment]
Well, the thing is, if the readme for a game says that it supports "ATI 3D Rage Pro", it doesn't necessarily mean it also uses the ATI3DCIF API. It may also use Direct3D, which should still run on pretty much any graphics card. I've used [this list](http://www.vogons.org/viewtopic.php?t=33483) to find the games that _only_ run on ATI3DCIF (marked green) and tried to support those for now (TR1 isn't marked, but it's technically exclusive for Win95). The other ones probably run better without a wrapper.
